export type Category = 'all' | 'men' | 'women' | 'couple' | 'kids' | 'landscapes' | 'scifi';

export interface Prompt {
  id: string;
  title: string;
  category: Exclude<Category, 'all'>;
  content: string;
  image: string;
  tags: string[];
  upvotes: number;
  createdAt: string;
}

export const categories: { id: Category; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'men', label: 'Men' },
  { id: 'women', label: 'Women' },
  { id: 'couple', label: 'Couple' },
  { id: 'kids', label: 'Kids' },
  { id: 'landscapes', label: 'Landscapes' },
  { id: 'scifi', label: 'Sci-Fi' },
];

export const mockPrompts: Prompt[] = [
  // ========== MEN ==========
  {
    id: '1',
    title: 'Cinematic Portrait Master',
    category: 'men',
    content: 'A distinguished gentleman in his 40s, wearing a perfectly tailored charcoal wool suit, standing in a dimly lit whiskey bar. Dramatic Rembrandt lighting, shallow depth of field, shot on Hasselblad medium format camera, cinematic color grading with warm amber tones.',
    image: 'A hyper-realistic cinematic editorial portrait of a distinguished gentleman in his 40s in a dark moody studio, surrounded by soft drifting smoke. He wears a perfectly tailored charcoal wool suit, standing with refined confidence as dramatic Rembrandt lighting sculpts his features.',
    tags: ['portrait', 'cinematic', 'professional'],
    upvotes: 342,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Urban Street Style',
    category: 'men',
    content: 'A young creative director leaning against graffiti-covered walls in Brooklyn. Wearing vintage denim jacket over a crisp white tee, raw street photography style. Overcast natural lighting, Fujifilm X-T4 film simulation, gritty urban aesthetic.',
    image: 'A hyper-realistic cinematic editorial portrait of a young creative director in a dark moody studio, surrounded by soft drifting smoke. He wears a vintage denim jacket over a crisp white tee, leaning casually with urban confidence and artistic flair.',
    tags: ['street', 'urban', 'casual'],
    upvotes: 234,
    createdAt: '2024-01-09',
  },
  {
    id: '3',
    title: 'The Modern Maverick',
    category: 'men',
    content: 'A candid, editorial-style portrait of a man in his late 30s with a salt-and-pepper beard, dressed in a textured cashmere sweater and a vintage Barbour jacket. He is leaning against a classic Land Rover Defender in the Scottish Highlands, with rolling hills and soft, overcast daylight creating a moody atmosphere. His expression is thoughtful and relaxed. The image should have a natural film grain texture, shallow depth of field, and an analog photography feel, capturing a sense of quiet luxury and rugged sophistication. Shot on Portra 400 film.',
    image: 'A hyper-realistic cinematic editorial portrait of a man in his late 30s with a salt-and-pepper beard in a dark moody studio, surrounded by soft drifting smoke. He wears a textured cashmere sweater and vintage Barbour jacket, exuding quiet luxury and rugged sophistication.',
    tags: ['old money', 'quiet luxury', 'editorial'],
    upvotes: 567,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    title: 'The Cyber-Tech Specialist',
    category: 'men',
    content: 'A hyper-realistic close-up portrait of a tech specialist in a futuristic 2040s setting. The man has short, undercut hair and a geometric facial tattoo that faintly glows blue. He wears a tactical techwear jacket with integrated LEDs and wiring visible. His eyes are focused on a transparent holographic data display hovering in front of him, casting a cool blue and purple light on his face. The background is a bustling, rain-slicked Tokyo street at night with neon signs reflecting on wet surfaces. 8K resolution, highly detailed textures on skin and fabric, cinematic lighting.',
    image: 'A hyper-realistic cinematic editorial portrait of a tech specialist in a dark moody studio, surrounded by soft drifting smoke. He has short undercut hair and a geometric facial tattoo that glows blue, wearing a tactical techwear jacket with integrated LEDs casting cool light on his face.',
    tags: ['cyberpunk', 'techwear', 'futuristic'],
    upvotes: 723,
    createdAt: '2024-01-19',
  },
  {
    id: '5',
    title: 'The Noir Detective',
    category: 'men',
    content: 'A gritty, black and white film noir photograph of a private detective sitting in a smoke-filled office at night. Rain streaks heavily down the window behind him, blurring neon city lights. He wears a rumpled trench coat and fedora, holding a lit cigarette. Dramatic chiaroscuro lighting from a desk lamp casts deep shadows across his weathered face. A half-empty bottle of whiskey and scattered case files are on the desk. The image has heavy film grain, high contrast, and the aesthetic of a 1940s crime thriller.',
    image: 'A hyper-realistic cinematic editorial portrait of a noir detective in a dark moody studio, surrounded by soft drifting smoke. He wears a rumpled trench coat and fedora, holding a lit cigarette as dramatic chiaroscuro lighting casts deep shadows across his weathered, world-weary face.',
    tags: ['noir', 'vintage', 'cinematic'],
    upvotes: 489,
    createdAt: '2024-01-18',
  },
  {
    id: '6',
    title: 'The Last Samurai',
    category: 'men',
    content: 'An epic, wide-angle cinematic shot of a lone samurai warrior standing on a rocky cliff edge during a violent thunderstorm. He is armored in traditional Japanese O-yoroi armor, ragged from battle, holding a katana bathed in lightning. Waves crash violently against the cliffs below. Dark, turbulent clouds fill the sky, pierced by jagged lightning bolts that illuminate the scene in flashes of blue and white light. The atmosphere is tense and powerful, with a desaturated, gritty color grade.',
    image: 'A hyper-realistic cinematic editorial portrait of a samurai warrior in a dark moody studio, surrounded by soft drifting smoke. He stands in traditional O-yoroi armor, ragged from battle, gripping his katana with intense determination as dramatic lighting illuminates his warrior spirit.',
    tags: ['samurai', 'action', 'cinematic'],
    upvotes: 892,
    createdAt: '2024-01-17',
  },
  {
    id: '7',
    title: 'The Arctic Explorer',
    category: 'men',
    content: 'A powerful wildlife photograph of an arctic explorer making eye contact with a massive polar bear across a patch of melting sea ice. The explorer is bundled in red technical gear, holding a camera with a long lens. The polar bear is curious, sniffing the air. The backdrop is a dramatic glacier and a freezing, dark blue ocean under a cloudy sky. The photo captures the tension, respect, and harsh beauty of the arctic environment.',
    image: 'A hyper-realistic cinematic editorial portrait of an arctic explorer in a dark moody studio, surrounded by soft drifting smoke. He is bundled in red technical gear, holding a camera with a long lens, his weathered face showing the determination of someone who has faced the frozen wilderness.',
    tags: ['adventure', 'wildlife', 'exploration'],
    upvotes: 634,
    createdAt: '2024-01-16',
  },

  // ========== WOMEN ==========
  {
    id: '8',
    title: 'Ethereal Fashion Editorial',
    category: 'women',
    content: 'An elegant model wearing a flowing silk gown in dusty rose, standing in an abandoned baroque palace. Golden hour light streaming through tall arched windows, particles of dust visible in the air. Shot in the style of Annie Leibovitz, 85mm lens, f/1.4 aperture.',
    image: 'A hyper-realistic cinematic editorial portrait of an elegant model in a dark moody studio, surrounded by soft drifting smoke. She wears a flowing silk gown in dusty rose, standing with ethereal grace as golden light illuminates the delicate fabric and her serene expression.',
    tags: ['fashion', 'editorial', 'elegant'],
    upvotes: 528,
    createdAt: '2024-01-14',
  },
  {
    id: '9',
    title: 'Minimalist Beauty Portrait',
    category: 'women',
    content: 'A close-up beauty portrait with flawless skin and natural makeup. Clean white studio background, soft butterfly lighting setup. Emphasis on skin texture and natural beauty, shot on Phase One IQ4 150MP, beauty retouching in style of Mario Testino.',
    image: 'A hyper-realistic cinematic editorial close-up portrait of a woman in a dark moody studio, surrounded by soft drifting smoke. Her flawless skin and natural makeup are illuminated by soft butterfly lighting, emphasizing natural beauty with stunning skin texture.',
    tags: ['beauty', 'minimalist', 'studio'],
    upvotes: 445,
    createdAt: '2024-01-08',
  },
  {
    id: '10',
    title: 'The Ethereal Goddess',
    category: 'women',
    content: 'A fantastical, dreamlike portrait of a woman with flowing, waist-length hair adorned with small, glowing bioluminescent flowers and crystals. She wears a gown made of iridescent, translucent silk that appears to be woven from moonlight. She is standing in an ancient, moss-covered forest grove at twilight, with soft golden light filtering through the canopy and fireflies drifting around her. Her expression is serene and powerful. The style should be painterly and ethereal, like a classical oil painting brought to life, with a soft focus and magical atmosphere.',
    image: 'A hyper-realistic cinematic editorial portrait of an ethereal goddess in a dark moody studio, surrounded by soft drifting smoke. She has flowing waist-length hair adorned with glowing bioluminescent flowers, wearing an iridescent silk gown that seems woven from moonlight itself.',
    tags: ['fantasy', 'ethereal', 'magical'],
    upvotes: 756,
    createdAt: '2024-01-20',
  },
  {
    id: '11',
    title: 'The Urban Creative',
    category: 'women',
    content: 'A vibrant, candid street style photograph of a young woman with dyed copper-orange hair in a shag cut. She is laughing naturally while walking across a busy crosswalk in Brooklyn, wearing oversized vintage denim overalls, a graphic band tee, and chunky platform sneakers. She carries a canvas tote bag covered in enamel pins and holds an iced coffee. The background shows yellow taxi cabs and brownstone buildings. The image has a bright, sunny daylight feel with saturated colors, natural film grain, and a candid, documentary-style composition.',
    image: 'A hyper-realistic cinematic editorial portrait of a young creative woman in a dark moody studio, surrounded by soft drifting smoke. She has dyed copper-orange hair in a shag cut, wearing oversized vintage denim overalls and laughing naturally with infectious energy.',
    tags: ['street style', 'gen z', 'candid'],
    upvotes: 623,
    createdAt: '2024-01-19',
  },
  {
    id: '12',
    title: 'Dark Academia Librarian',
    category: 'women',
    content: 'A moody, atmospheric portrait of a young historian in a dusty, candelabra-lit chamber of an ancient university library. She wears tweed trousers and a dark wool blazer, holding an open, leather-bound grimoire. Dust motes dance in shafts of moonlight entering through a tall Gothic window. Shelves overflow with old books, taxidermy ravens, and alchemical tools. The color palette is muted deep browns, forest greens, and aged gold. Photographed on analog film with natural light and a shallow depth of field.',
    image: 'A hyper-realistic cinematic editorial portrait of a young historian in a dark moody studio, surrounded by soft drifting smoke. She wears tweed trousers and a dark wool blazer, holding an open leather-bound grimoire with an expression of scholarly intensity.',
    tags: ['dark academia', 'moody', 'vintage'],
    upvotes: 534,
    createdAt: '2024-01-18',
  },
  {
    id: '13',
    title: 'High-Fashion Futuristic Nomad',
    category: 'women',
    content: 'A striking, high-fashion editorial shot of a nomadic model in a desert landscape at sunset. She wears avant-garde clothing made of layered deconstructed fabrics, reflective thermal blankets, and scavenged technical gear. Her face has geometric white paint markings. She stands atop a sand dune, holding a staff wrapped in wires. The lighting is dramatic golden hour sun, creating long shadows. The photo has a textured, raw feel, like a page from a luxury fashion magazine, shot on medium format film.',
    image: 'A hyper-realistic cinematic editorial portrait of a futuristic nomadic model in a dark moody studio, surrounded by soft drifting smoke. She wears avant-garde deconstructed fabrics with geometric white paint markings on her face, holding a wire-wrapped staff with fierce determination.',
    tags: ['high fashion', 'editorial', 'avant-garde'],
    upvotes: 678,
    createdAt: '2024-01-17',
  },
  {
    id: '14',
    title: 'Post-Apocalyptic Survivor',
    category: 'women',
    content: 'A gritty, close-up portrait of a female survivor in a post-apocalyptic wasteland. Her face is smudged with dirt and grease, wearing makeshift goggles pushed up onto her forehead. She wears patched leather gear and carries a scavenged rifle. In the background, there are rusted ruins of skyscrapers and a dust storm approaching. Her eyes look tired but determined. The photo has a desaturated, bleach-bypass look with extreme detail on skin pores and fabric textures.',
    image: 'A hyper-realistic cinematic editorial portrait of a female survivor in a dark moody studio, surrounded by soft drifting smoke. Her face is smudged with dirt and grease, wearing makeshift goggles on her forehead and patched leather gear, her eyes tired but fiercely determined.',
    tags: ['post-apocalyptic', 'gritty', 'survivor'],
    upvotes: 512,
    createdAt: '2024-01-16',
  },

  // ========== COUPLE ==========
  {
    id: '15',
    title: 'Romantic Garden Moment',
    category: 'couple',
    content: 'A couple dancing in a moonlit English garden surrounded by blooming roses and wisteria. Soft bokeh fairy lights in the background, romantic dreamy atmosphere. Shot on analog film with natural light leaks, pastel color palette.',
    image: 'A hyper-realistic cinematic editorial portrait of a couple in a dark moody studio, surrounded by soft drifting smoke. They are captured mid-dance, wrapped in each other\'s arms with romantic intensity, soft light creating an intimate atmosphere.',
    tags: ['romantic', 'garden', 'dreamy'],
    upvotes: 456,
    createdAt: '2024-01-13',
  },
  {
    id: '16',
    title: 'The Cinematic Romance',
    category: 'couple',
    content: 'A romantic, cinematic photograph of a couple caught in a passionate embrace on a rainy evening in Paris. They are under a single shared umbrella, standing on a cobblestone bridge over the Seine river. The Eiffel Tower is visible but softly blurred in the distance, illuminated against a deep blue twilight sky. Wet pavement reflects the warm glow of streetlamps and cafe lights. The image should have a moody, intimate atmosphere, with a shallow depth of field, visible film grain, and a color grade emphasizing deep blues, oranges, and warm shadows. Shot on Kodak Portra 800.',
    image: 'A hyper-realistic cinematic editorial portrait of a couple in a dark moody studio, surrounded by soft drifting smoke. They are caught in a passionate embrace under a shared umbrella, their faces close together with deep romantic intensity.',
    tags: ['paris', 'romantic', 'cinematic'],
    upvotes: 834,
    createdAt: '2024-01-20',
  },
  {
    id: '17',
    title: 'The Adventure Duo',
    category: 'couple',
    content: 'An adventurous lifestyle shot of a couple hiking on a mountain ridge at sunrise. Both are wearing technical outdoor gear from brands like Patagonia and Arc\'teryx, including backpacks and hiking boots. They are holding hands, looking out over a sea of clouds with jagged mountain peaks piercing through, bathed in warm golden light. Their faces are joyful and wind-swept. The photo should feel natural and inspiring, with sharp detail on the gear and landscape, wide-angle perspective, and a sense of grand scale and freedom.',
    image: 'A hyper-realistic cinematic editorial portrait of an adventurous couple in a dark moody studio, surrounded by soft drifting smoke. Both wear technical outdoor gear with backpacks, holding hands with joyful, wind-swept expressions of shared adventure.',
    tags: ['adventure', 'gorpcore', 'outdoors'],
    upvotes: 745,
    createdAt: '2024-01-19',
  },

  // ========== KIDS ==========
  {
    id: '18',
    title: 'Whimsical Childhood Wonder',
    category: 'kids',
    content: 'A curious 5-year-old child exploring a sunlit meadow filled with wildflowers and butterflies. Golden hour backlighting creating a magical halo effect. Shot in the style of Elena Shumilova, soft focus, warm nostalgic color grading.',
    image: 'A hyper-realistic cinematic editorial portrait of a curious 5-year-old child in a dark moody studio, surrounded by soft drifting smoke. Golden backlight creates a magical halo effect around them as they gaze with wonder-filled eyes.',
    tags: ['whimsical', 'childhood', 'nature'],
    upvotes: 289,
    createdAt: '2024-01-12',
  },
  {
    id: '19',
    title: 'The Whimsical Explorer',
    category: 'kids',
    content: 'A 3D animated still in the style of Pixar, showing a cute 5-year-old kid with messy brown hair and oversized aviator goggles pushed up on their forehead. They are wearing a patched-up cardboard robot costume and standing in a backyard that has been transformed into a magical jungle with giant, colorful plants made of household items. The kid is holding a magnifying glass, looking curiously at a glowing, magical beetle. The lighting is bright and warm, with soft, inviting textures, playful character design, and a sense of wonder and imagination.',
    image: 'A hyper-realistic cinematic editorial portrait of a cute 5-year-old explorer in a dark moody studio, surrounded by soft drifting smoke. They have messy brown hair with oversized aviator goggles on their forehead, wearing a cardboard robot costume and holding a magnifying glass with curious wonder.',
    tags: ['pixar', '3d', 'whimsical'],
    upvotes: 678,
    createdAt: '2024-01-20',
  },
  {
    id: '20',
    title: 'The Vintage Childhood',
    category: 'kids',
    content: 'A nostalgic, film-like photo of two siblings, a boy and a girl aged roughly 6 and 8, playing in a sun-drenched field of tall grass. They are wearing retro 70s clothing: striped ringer tees and corduroy overalls. The boy is flying a colorful kite shaped like a dragon, and the girl is chasing it, laughing. The photo has a warm, desaturated color palette with sepia tones, light leaks, and heavy film grain, giving it the feeling of an authentic, treasured memory from a family photo album.',
    image: 'A hyper-realistic cinematic editorial portrait of two siblings in a dark moody studio, surrounded by soft drifting smoke. They wear retro 70s clothing with striped ringer tees and corduroy overalls, captured mid-laugh with pure childhood joy.',
    tags: ['nostalgic', 'vintage', '70s'],
    upvotes: 534,
    createdAt: '2024-01-19',
  },

  // ========== LANDSCAPES ==========
  {
    id: '21',
    title: 'Majestic Mountain Vista',
    category: 'landscapes',
    content: 'Dramatic panoramic view of the Swiss Alps at sunrise, with low-hanging clouds creating a sea below the peaks. Snow-capped mountains reflecting pink and orange light, ultra-wide angle shot, HDR photography, National Geographic style.',
    image: 'A hyper-realistic cinematic editorial photograph of a majestic mountain vista in a dark moody studio setting, surrounded by soft drifting smoke. The Swiss Alps emerge through atmospheric haze with snow-capped peaks reflecting pink and orange sunrise light.',
    tags: ['mountains', 'sunrise', 'panoramic'],
    upvotes: 672,
    createdAt: '2024-01-11',
  },
  {
    id: '22',
    title: 'Nordic Winter Wonderland',
    category: 'landscapes',
    content: 'Northern Lights dancing over a frozen Norwegian fjord, snow-covered pine trees in the foreground. Long exposure capturing aurora movement, midnight blue and emerald green colors, pristine untouched snow. Shot in -20°C conditions.',
    image: 'A hyper-realistic cinematic editorial photograph of the Northern Lights in a dark moody studio setting, surrounded by soft drifting smoke. The aurora dances in midnight blue and emerald green over snow-covered pine trees silhouetted against the ethereal glow.',
    tags: ['aurora', 'winter', 'nordic'],
    upvotes: 723,
    createdAt: '2024-01-06',
  },
  {
    id: '23',
    title: 'The Surrealistic Dreamscape',
    category: 'landscapes',
    content: 'A surreal, breathtaking landscape showing a desert where the sand dunes are made of swirling pastel colors like pink, mint green, and lavender. Instead of cacti, giant, translucent crystal formations in geometric shapes grow from the ground, refracting the light of two moons visible in a violet sky. A river of liquid gold flows through the center of the scene. The lighting is ethereal and diffused, creating a dreamlike, impossible world that challenges reality. Highly detailed render with a focus on texture and light refraction.',
    image: 'A hyper-realistic cinematic editorial photograph of a surrealistic dreamscape in a dark moody studio setting, surrounded by soft drifting smoke. Pastel-colored sand dunes swirl with pink, mint green, and lavender as translucent crystal formations refract ethereal light.',
    tags: ['surreal', 'dreamscape', 'abstract'],
    upvotes: 867,
    createdAt: '2024-01-20',
  },
  {
    id: '24',
    title: 'The Bioluminescent Cove',
    category: 'landscapes',
    content: 'A fantastical landscape photograph of a secret ocean cove at night where the water glows an intense electric blue due to bioluminescent plankton. Massive, ancient tree roots gnarled into archways drape over the water, covered in glowing moss and purple glowing mushrooms. A small, wooden rowboat with a lantern sits in the center of the glowing water. A full moon is partially obscured by clouds. The style is magical realism, long exposure photography, with vibrant, saturated colors and razor-sharp detail.',
    image: 'A hyper-realistic cinematic editorial photograph of a bioluminescent cove in a dark moody studio setting, surrounded by soft drifting smoke. Electric blue glowing water illuminates ancient gnarled tree roots covered in purple glowing mushrooms.',
    tags: ['bioluminescent', 'fantasy', 'magical'],
    upvotes: 945,
    createdAt: '2024-01-19',
  },
  {
    id: '25',
    title: 'Brutalist Jungle Home',
    category: 'landscapes',
    content: 'An architectural photograph of a brutalist concrete house embedded deep within a lush tropical jungle. Raw, imposing concrete geometric structures are softened by creeping monstera plants, ferns, and hanging vines taking over the facade. An infinity pool reflects the dense canopy above. Large glass walls connect the raw interior with the humid exterior. It is raining lightly, making the concrete surfaces look dark and wet. The mood is serene, ancient, and architectural, emphasizing the contrast between man-made gray and natural green.',
    image: 'A hyper-realistic cinematic editorial photograph of a brutalist jungle home in a dark moody studio setting, surrounded by soft drifting smoke. Raw concrete geometric structures emerge through creeping monstera plants and hanging vines, wet from rain.',
    tags: ['brutalist', 'architecture', 'jungle'],
    upvotes: 712,
    createdAt: '2024-01-18',
  },
  {
    id: '26',
    title: 'Cottagecore Bakery',
    category: 'landscapes',
    content: 'Inside a rustic, warm cottagecore bakery kitchen bathed in morning light. Wooden counters are piled high with freshly baked sourdough loaves, pastries, and jars of homemade jam. Dried herbs and copper pots hang from ceiling beams. A cat sleeps on a windowsill next to potted geraniums. An elderly woman with a flour-dusted apron is kneading dough. The atmosphere is warm, cluttered, and inviting. Shot on film with a soft, natural color palette and intentional grain.',
    image: 'A hyper-realistic cinematic editorial photograph of a cottagecore bakery interior in a dark moody studio setting, surrounded by soft drifting smoke. Warm light illuminates wooden counters piled with freshly baked sourdough loaves and copper pots hanging from beams.',
    tags: ['cottagecore', 'cozy', 'bakery'],
    upvotes: 623,
    createdAt: '2024-01-17',
  },
  {
    id: '27',
    title: 'Minimalist Zen Garden',
    category: 'landscapes',
    content: 'An ultra-minimalist architectural photograph of a modern Japanese Zen garden. A single, perfectly shaped bonsai tree sits on a moss island surrounded by meticulously raked white gravel in concentric circles. A smooth concrete wall with a circular opening frames a view of a misty mountain. The composition is perfectly balanced and symmetrical. The light is soft, diffused overcast daylight. The mood is tranquil, silent, and focused on negative space.',
    image: 'A hyper-realistic cinematic editorial photograph of a minimalist Zen garden in a dark moody studio setting, surrounded by soft drifting smoke. A perfectly shaped bonsai tree sits on a moss island surrounded by meticulously raked white gravel in concentric circles.',
    tags: ['zen', 'minimalist', 'japanese'],
    upvotes: 534,
    createdAt: '2024-01-16',
  },
  {
    id: '28',
    title: 'Abstract Fluid Art',
    category: 'landscapes',
    content: 'A mesmerizing abstract photograph of swirling colored liquids and ferrofluid reacting to magnets. Deep blues, metallic golds, pearlescent whites, and vibrant oranges mix in complex, organic patterns resembling cellular structures and galaxies. The textures are glossy and oily. The lighting is studio quality, highlighting the depth and reflective surfaces of the liquids. It is an explosive macro shot focusing on color interaction and fluid dynamics.',
    image: 'A hyper-realistic cinematic editorial photograph of abstract fluid art in a dark moody studio setting, surrounded by soft drifting smoke. Deep blues, metallic golds, and vibrant oranges swirl in complex organic patterns with glossy, oily textures.',
    tags: ['abstract', 'fluid art', 'macro'],
    upvotes: 456,
    createdAt: '2024-01-15',
  },
  {
    id: '29',
    title: 'Macro Insect Kingdom',
    category: 'landscapes',
    content: 'An incredible macro photograph of a jewel beetle sitting on a dew-covered moss spore. The image is so close that you can see the individual iridescent scales on the beetle\'s carapace reflecting a spectrum of colors like oil on water. The water droplets are perfectly spherical mirrors. The background is a creamy, blurred bokeh of greens and golds. The focus is razor-sharp on the insect\'s eyes. Natural morning light, National Geographic quality aesthetic.',
    image: 'A hyper-realistic cinematic editorial photograph of a jewel beetle in a dark moody studio setting, surrounded by soft drifting smoke. The iridescent scales on the beetle\'s carapace reflect a spectrum of colors like oil on water, razor-sharp focus on its compound eyes.',
    tags: ['macro', 'nature', 'wildlife'],
    upvotes: 678,
    createdAt: '2024-01-14',
  },
  {
    id: '30',
    title: '1980s Mall Madness',
    category: 'landscapes',
    content: 'A vibrant, chaotic photograph inside an American shopping mall in 1985. Teenagers with big hair and acid-wash jeans crowd around an arcade. Neon signs for "Orange Julius" and "Sam Goody" glow brightly. The floor is patterned terrazzo. A fountain in the center is filled with pennies. The photo has the distinct aesthetic of 80s film stock: saturated colors, slight magenta tint, and flash photography lighting, capturing a moment of pure teenage nostalgia.',
    image: 'A hyper-realistic cinematic editorial photograph of an 80s shopping mall interior in a dark moody studio setting, surrounded by soft drifting smoke. Neon signs glow with saturated colors and slight magenta tint, capturing pure teenage nostalgia.',
    tags: ['80s', 'nostalgic', 'retro'],
    upvotes: 589,
    createdAt: '2024-01-13',
  },

  // ========== SCI-FI ==========
  {
    id: '31',
    title: 'Cyberpunk Metropolis',
    category: 'scifi',
    content: 'A sprawling neon-lit cyberpunk cityscape in 2087, holographic advertisements floating between impossibly tall skyscrapers. Flying vehicles leaving light trails, rain-slicked streets reflecting countless colors. Blade Runner meets Ghost in the Shell aesthetic.',
    image: 'A hyper-realistic cinematic editorial photograph of a cyberpunk metropolis in a dark moody studio setting, surrounded by soft drifting smoke. Neon-lit skyscrapers and holographic advertisements reflect off rain-slicked surfaces with Blade Runner aesthetic.',
    tags: ['cyberpunk', 'futuristic', 'neon'],
    upvotes: 891,
    createdAt: '2024-01-10',
  },
  {
    id: '32',
    title: 'Space Station Observatory',
    category: 'scifi',
    content: 'Interior of a futuristic space station observation deck, with a massive curved window showing Earth and the Milky Way. Astronaut floating weightlessly, bioluminescent plant installations, clean minimalist design inspired by Apple and SpaceX aesthetics.',
    image: 'A hyper-realistic cinematic editorial photograph of a space station observatory in a dark moody studio setting, surrounded by soft drifting smoke. A curved observation window reveals Earth and the Milky Way with clean minimalist Apple-inspired design.',
    tags: ['space', 'futuristic', 'minimal'],
    upvotes: 567,
    createdAt: '2024-01-07',
  },
  {
    id: '33',
    title: 'The Neo-Terra City',
    category: 'scifi',
    content: 'A wide-angle landscape of a futuristic "solarpunk" city built in harmony with nature. Skyscrapers are constructed from timber, glass, and polished green stone, covered in vertical gardens, cascading waterfalls, and solar panels that look like glass leaves. Airships with sail-like solar wings drift between the towers. Pedestrian bridges connect buildings, filled with people and lush greenery. The city is nestled in a valley with a clear blue river. The lighting is bright and optimistic, with a clear blue sky, conveying a sense of a sustainable, utopian future. 8K resolution, highly detailed architecture.',
    image: 'A hyper-realistic cinematic editorial photograph of a solarpunk city in a dark moody studio setting, surrounded by soft drifting smoke. Timber and glass skyscrapers covered in vertical gardens and cascading waterfalls glow with optimistic, sustainable energy.',
    tags: ['solarpunk', 'utopian', 'futuristic'],
    upvotes: 923,
    createdAt: '2024-01-20',
  },
  {
    id: '34',
    title: 'Cyberpunk Street Market',
    category: 'scifi',
    content: 'A bustling, chaotic street market in a futuristic cyberpunk mega-city at night. The scene is drenched in neon signs with Japanese and Cyrillic characters reflecting off wet pavement and holographic advertisements advertising cybernetics. Vendors sell strange, glowing street food from stalls built out of recycled tech. Diverse crowds of people with glowing fashion and robotic limbs navigate the mud. Overhead, flying vehicles traverse tight alleyways between towering skyscrapers. 8K resolution, incredibly dense detail, volumetric fog, cinematic lighting.',
    image: 'A hyper-realistic cinematic editorial photograph of a cyberpunk street market in a dark moody studio setting, surrounded by soft drifting smoke. Neon signs with Japanese characters reflect off wet pavement as vendors sell glowing street food from recycled tech stalls.',
    tags: ['cyberpunk', 'market', 'neon'],
    upvotes: 856,
    createdAt: '2024-01-19',
  },
  {
    id: '35',
    title: 'The Deep Space Hauler',
    category: 'scifi',
    content: 'A highly detailed exterior shot of a massive, industrial deep-space mining vessel drifting past the rings of Saturn. The ship is utilitarian, covered in exposed pipes, cargo containers, radar dishes, and scorch marks from micrometeoroids. Its massive engines glow with a soft blue plasma output. The sunlight catches the ice particles in Saturn\'s rings. The scale is immense. 8K resolution, photorealistic render (like Unreal Engine 5), hard sci-fi aesthetic.',
    image: 'A hyper-realistic cinematic editorial photograph of a deep space hauler vessel in a dark moody studio setting, surrounded by soft drifting smoke. The massive industrial mining ship is covered in exposed pipes and scorch marks, engines glowing with soft blue plasma.',
    tags: ['space', 'hard sci-fi', 'industrial'],
    upvotes: 789,
    createdAt: '2024-01-18',
  },
  {
    id: '36',
    title: 'Retro-Futuristic Diner',
    category: 'scifi',
    content: 'A stylized photo of a 1950s-style American diner with a retro-futuristic twist. Chrome robot servers on wheels serve milkshakes to patrons wearing bubble helmets and vintage space suits. Outside the large curved window, fin-tailed flying cars are parked at a drive-in. The architecture features raygun gothic designs and atomic age motifs. The color palette is pastel blues, pinks, and mint greens with polished chrome accents. The look is warm, nostalgic, like a faded Kodachrome photograph.',
    image: 'A hyper-realistic cinematic editorial photograph of a retro-futuristic diner in a dark moody studio setting, surrounded by soft drifting smoke. Chrome robot servers and atomic age motifs blend with pastel blues, pinks, and polished chrome accents.',
    tags: ['retro-futuristic', 'diner', 'atomic age'],
    upvotes: 678,
    createdAt: '2024-01-17',
  },
  {
    id: '37',
    title: 'Neon Tokyo Rain',
    category: 'scifi',
    content: 'A candid street photograph taken through the rain-streaked windshield of a taxi in Shinjuku, Tokyo at night. The outside world is a blur of colorful bokeh from neon signs and brake lights. Pedestrians with transparent umbrellas hurry across a crosswalk. The focus is on the water droplets on the glass, with the vibrant city lights smeared behind them. The mood is cinematic, moody, and urban, emphasizing light and color saturation.',
    image: 'A hyper-realistic cinematic editorial photograph of neon Tokyo rain in a dark moody studio setting, surrounded by soft drifting smoke. Water droplets on glass blur colorful bokeh from neon signs and brake lights into a moody urban dreamscape.',
    tags: ['tokyo', 'cyberpunk', 'urban'],
    upvotes: 723,
    createdAt: '2024-01-16',
  },
  {
    id: '38',
    title: 'Isometric Cozy Gaming Room',
    category: 'scifi',
    content: 'A cute, highly detailed isometric 3D render of a cozy gaming room at night. The room contains a desk with a dual-monitor setup displaying a pixel art game, a mechanical keyboard with RGB lighting, shelves filled with manga and retro consoles, a plush beanbag chair with a sleeping cat, and string lights hanging across the ceiling. Rain is visible outside a small window. The style is warm, inviting, "lo-fi hip hop radio" aesthetic, with soft baked lighting and clay-like textures.',
    image: 'A hyper-realistic cinematic editorial 3D render of an isometric cozy gaming room in a dark moody studio setting, surrounded by soft drifting smoke. Dual monitors glow with RGB lighting, shelves filled with manga and retro consoles creating lo-fi aesthetic.',
    tags: ['isometric', '3d', 'cozy'],
    upvotes: 645,
    createdAt: '2024-01-15',
  },
  {
    id: '39',
    title: 'Steampunk Inventor\'s Workshop',
    category: 'scifi',
    content: 'Inside a cluttered steampunk workshop filled with brass gears, copper piping, and bubbling glass vials. An inventor with leather apron and magnifying goggles is working on a clockwork automaton bird that is half-assembled on a workbench. Blueprints cover the walls. Steam rises from various contraptions. The lighting is warm and golden from gas lamps and Edison bulbs. The level of detail is immense, with every tool and cog visible in a rich, textural style.',
    image: 'A hyper-realistic cinematic editorial photograph of a steampunk inventor\'s workshop in a dark moody studio setting, surrounded by soft drifting smoke. Brass gears, copper piping, and bubbling glass vials fill the space with warm golden light from gas lamps.',
    tags: ['steampunk', 'workshop', 'vintage'],
    upvotes: 567,
    createdAt: '2024-01-14',
  },
  {
    id: '40',
    title: 'The Crystal Dragon',
    category: 'scifi',
    content: 'A majestic full-body shot of a massive dragon made entirely of jagged, translucent quartz and amethyst crystals. It is perched on a snowy mountain peak. Sunlight refracts through its crystalline body, casting rainbows onto the snow around it. Its eyes glow with internal magical energy. The environment is frozen and harsh. The style is a high-fantasy digital painting with a focus on light refraction and sharp, geological textures.',
    image: 'A hyper-realistic cinematic editorial photograph of a crystal dragon in a dark moody studio setting, surrounded by soft drifting smoke. The majestic dragon made of translucent quartz and amethyst refracts light through its crystalline body, eyes glowing with magical energy.',
    tags: ['fantasy', 'dragon', 'crystal'],
    upvotes: 934,
    createdAt: '2024-01-13',
  },
];
